config/routes.rb
Rails.application.routes.draw do
  root to: 'stocks#index'
  # resources :stocks, except: :index
  resources :stocks do
    resources :gifts, only: [:create, :destroy]
    resources :dividends, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dividend.rb
class Dividend < ApplicationRecord
  validates :dividend, presence: true
  validates :stock_num, presence: true

  belongs_to :stock
end

app/models/gift.rb
class Gift < ApplicationRecord
  validates :gift_name, presence: true
  belongs_to :stock
end

app/models/stock.rb
class Stock < ApplicationRecord
  validates :stock_code, presence: true, length: { mimimum:4, maximum: 4, message: '4 digits!' }
  validates :name, presence: true

  has_many :gifts, dependent: :destroy
  has_many :dividends, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dividends_controller.rb
class DividendsController < ApplicationController

  def create

    @stock = Stock.find(params[:stock_id])
    @stock.dividends.create(dividend_params)
    redirect_to root_path

  end

  def destroy
    @stock = Stock.find(params[:stock_id])
    @dividend = @stock.dividends.find(params[:id])
    @dividend.destroy
    redirect_to root_path
  end

  private
  def dividend_params
    params.require(:dividend).permit(:dividend, :stock_num, :year_month, :comment)
  end

end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController

  def create
    @stock = Stock.find(params[:stock_id])
    @stock.gifts.create(gift_params)
    redirect_to root_path
  end

  def destroy
    @stock = Stock.find(params[:stock_id])
    @gift = @stock.gifts.find(params[:id])
    @gift.destroy
    redirect_to root_path
  end

  private
  def gift_params
    params.require(:gift).permit(:gift_name, :value, :year_month, :comment)
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def index
    # @stocks = Stock.all.order(stock_code: 'asc')
    # @stocks = Stock.all.order(created_at: 'desc')
    @stocks = Stock.all.order("created_at DESC").page(params[:page]).per(10)
    
  end

  def show
    @stock = Stock.find(params[:id])
  end

  def new
    @stock = Stock.new
  end

  def create
    Stock.create(stock_params)
    redirect_to root_path
  end

  def edit
    @stock = Stock.find(params[:id])
  end

  def update
    stock = Stock.find(params[:id])
    stock.update(stock_params)
    redirect_to stock_path(stock.id)
  end

  def destroy
    stock = Stock.find(params[:id])
    stock.destroy
    redirect_to root_path
  end


  private
  def stock_params
    params.require(:stock).permit(:stock_code, :name)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dividends_helper.rb
module DividendsHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<%# アプリ全体のレイアウトはこちら %>
<%# CSSはapplication.css %>

<!DOCTYPE html>
<html>
  <head>
    <title>StockShow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%# bootstrapを入れ以下の２行適用中 %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
  </head>

  <body>
    <div class="container">
      <h3><%= link_to image_tag('inu.png', class: 'logo'), root_path %></h3>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with model: @stock do |form| %>
<p>
  <%= form.text_field :stock_code, placeholder: 'stock code 4 digits' %>
</p>
<p>
  <%= form.text_field :name, placeholder: "company's name" %>
</p>
<p>
  <%= form.submit %>
</p>
<% end %>

app/views/stocks/edit.html.erb
<h2>内容の訂正</h2>

<%= render 'form' %>

app/views/stocks/index.html.erb
<h2>
  <%= link_to '株の登録', new_stock_path, class: 'header-menu' %> 
  Stock Show
</h2>

<ul class="index-ul">
  <% @stocks.each do |stock| %>
    <li class="index-li">
      <%= stock.stock_code %>
      <%= link_to "#{stock.name}の詳細へ", stock_path(stock.id) %>
    </li>
  <% end %>
</ul>

<%= paginate(@stocks) %>

app/views/stocks/new.html.erb
<h2>株の登録</h2>

<%= render 'form' %>

app/views/stocks/show.html.erb
<h2>
<%= link_to "削除", stock_path(@stock.id), method: :delete, class: "header-menu delete-btn", data: { confirm: '削除してよろしいですか？' }%>
<%= link_to '内容訂正', edit_stock_path, class: 'header-menu' %> 

<%= @stock.stock_code %>
</h2>
<h1 class="stock-name"><%= @stock.name %></h1>

<div class="detailed-info">
  
  <div class="dividends">
    <h4>配当情報</h4>

    

  <% if @stock.dividends.any? %>
    <ul>
      <% @stock.dividends.each do |dividend| %>
        <li class="dividends-list">
          配当入金:<%= dividend.year_month.strftime('%Y年%m月') %>
          <p class="dividend-info">配当(一株あたり):<%= dividend.dividend %></p>
          <p class="dividend-info">保有株数:<%= dividend.stock_num %>株</p>
          
          <% total = dividend.dividend.to_i * dividend.stock_num.to_i %>
          <p class="total-dividend">今期配当合計:<%= total %>円</p>
          <p class="dividend-info">メモ:<%= dividend.comment %></P>
          <%= link_to "削除", stock_dividend_path(@stock, dividend), method: :delete, class: "header-menu delete-btn", data: { confirm: '削除してよろしいですか？' }%>
        </li>
      <% end %>
    </ul>
  <% end %>

    <%= form_for([@stock, @stock.dividends.build]) do |f| %>
    <p>
      <%= f.text_field :dividend, placeholder: '一株あたりの配当金額' %>
    </p>
    <p>
      <%= f.text_field :stock_num, placeholder: "保有株数" %>
    </p>
    <p>
      <%= f.text_area :comment, placeholder: "配当に関するメモ" %>
    </p>
    <p>
      <%= f.date_select :year_month, {discard_day: true} %>
    </p>
    <p>
      <%= f.submit "配当情報登録" %>
    </p>
    <% end %>


  </div>
  
  <div class="gifts">
    <h4>優待情報</h4>

  <% if @stock.gifts.any? %>
    <ul>
      <% @stock.gifts.each do |gift| %>
        <li class="gifts-list">
          優待品:<%= gift.gift_name %>
          <p>評価額:<%= gift.value %>円 優待到着:<%= gift.year_month.strftime('%Y年%m月') %></p>
          <p>メモ:<%= gift.comment %></P>
          <%= link_to "削除", stock_gift_path(@stock, gift), method: :delete, class: "header-menu delete-btn", data: { confirm: '削除してよろしいですか？' }%>
        </li>
      <% end %>
    </ul>
  <% end %>

    <%= form_for([@stock, @stock.gifts.build]) do |f| %>
    <p>
      <%= f.text_field :gift_name, placeholder: '優待品の詳細' %>
    </p>
    <p>
      <%= f.text_field :value, placeholder: "評価額" %>
    </p>
    <p>
      <%= f.text_area :comment, placeholder: "優待に関するメモ" %>
    </p>
    <p>
      <%= f.date_select :year_month, {discard_day: true} %>
    </p>
    <p>
      <%= f.submit "優待情報登録" %>
    </p>
    <% end %>

  </div>
</div>